name = "mari0_cc"
default_targets = ["win64"]
build_directory = "makelove-build"
icon_file = "graphics/icon.png"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]

# TODO: more metadata

[windows.exe_metadata]
ProductName = "Mari0: Crowd Control"

[linux.desktop_file_metadata]
Name = "Mari0: Crowd Control"

[macos.app_metadata]
CFBundleDisplayName = "Mari0: Crowd Control"
