name: Compile
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
        submodules: true
      name: Checkout Repository
    - name: Extract Metadata
      id: metadata
      run: python3 main/.scripts/extract-metadata.py
    - name: Add Universe Repository
      run: sudo add-apt-repository universe
    - name: Update Packages
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install --assume-yes wine-stable wine64 python3-pip libfuse2
    - name: Install makelove
      run: pip3 install --break-system-packages git+https://github.com/qixils/makelove/
    - name: Build
      run: cd main && python3 -m makelove && cd ..
    - name: Artifact (LÖVE)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.id }}-source
        path: main/makelove-build/love/${{ env.ARTIFACT_NAME_LOVE }}
    - name: Artifact (Win64)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.metadata.outputs.id }}-win64
        path: main/makelove-build/win64/${{ env.ARTIFACT_NAME_WIN64 }}
